### ISSUE TITLE
문서 내 목록을 정렬하는 규칙을 명시

### ISSUE THREAD

**Issue by koremp** [channy/korea-devculture#6]
깃허브를 사용하면서 이런 회사 관련 정보를 공유하는 레포지토리/사이트는 상위에 노출된 회사가 더 쉽게 이용자에게 접근할 수 있습니다. 

그렇기 때문에, 현재는 회사만 정리되어 있지만, 목록들을 정렬하는 규칙을 명시하였으면 하는 바입니다.

단순 회사의 Organization에 공개된 레포지토리만이 절대적인 기준이 될 수 없으리라 생각합니다.

회사의 개발문화나 컨퍼런스의 주최, 후원, 회사가 오픈소스를 얼마나 사용하고 있는지, 등을 정리하여 다양한 기준에 맞게 정렬할 수 있었으면 하는 바입니다.

**Comment by channy** [comment]
좋은 제안 감사합니다 이 레포는 제가 어떤 발표 자료 준비하면서 우라 나라에 org 레벨 github을 운영하는 회사가 얼마나 있는지 어떤 규모로 소스/문서를 송유하고 있는지 알고 싶어서 만들었습니다. 각 기업의 레포 중에 스타수가 많은 프로젝트가 무엇인지 그리고 얼마나 자주 기여가 일어나는지 활동성 정도의 데이터만 추가되면 좋을 것 같네요.

개발 문화의 다른 부분은 다른 영역에서 측정되면 좋겠다는 생각입니다.

**Comment by koremp** [comment]
친절한 대답 감사합니다.
